### ISSUE TITLE
Buttons not working on HZ-W09

### ISSUE THREAD

**Issue by datenhamster** [ivzave/matebook-linux#4]
tried the 0002-Patch on this device. Buttons not working with it. Is there something different with this device? How I am able to find this out?

**Comment by ivzave** [comment]
My device is HZ-W19 but I believe DSDT is same or at least similar. However iasl has evolved since that patch was introduced so the output of recent iasl is different from what the patch is intended for. I can't guarantee it gets applied correctly, this needs to be checked.

I'd check additionally that DSDT override does actually happen during boot (grep `dmesg` output for "DSDT"). I found out some time ago that with secure boot enabled the kernel doesn't use DSDT override so you probably need to disable secure boot in UEFI setup. This wasn't required at time of writing of README.

If DSDT override works then the problem could be in DSDT itself. It's worth checking actual DSDT against expectations of intel-hid kernel driver - this is what I did while preparing that patch. That driver also has evolved since patch first appeared so maybe more DSDT modifications are needed now or DSDT of your device differs from mine.

Hope that helps.

**Comment by datenhamster** [comment]
Ok, it took some time. I got it. Power Button and Volume are working.

I did:

sudo cp dsdt.aml /etc/initramfs-tools/DSDT.aml

and

sudo update-initramfs -u -k kernel-version

So, it works for now. Have to see with newer kernels.

Thanks for your work.
